name: 🧪 Runc integration test

on:
  workflow_dispatch:

jobs:
  youki-build:
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    strategy:
      matrix:
        arch: [ "x86_64", "aarch64" ]
        libc: [ "gnu", "musl" ]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Rust toolchain and cache
        uses: actions-rust-lang/setup-rust-toolchain@v1.3.7
        env:
          RUST_CACHE_KEY_OS: rust-cache-${{ matrix.arch }}-${{ matrix.libc }}
      - name: Install just
        uses: taiki-e/install-action@just
      - name: Install cross-rs
        run: RUSTFLAGS="" cargo install cross --git https://github.com/cross-rs/cross
      - name: Setup target
        run: |
          echo "CARGO=cross" >> ${GITHUB_ENV}
          echo "TARGET=${{ matrix.arch }}-unknown-linux-${{ matrix.libc }}" >> ${GITHUB_ENV}
      - name: Build youki
        run: just youki-release
      - name: Upload youki binary
        if: ${{ matrix.arch == 'x86_64' }}
        uses: actions/upload-artifact@v4
        with:
          name: youki-${{ matrix.arch }}-${{ matrix.libc }}
          path: youki

  runc-integration-tests:
    runs-on: ubuntu-24.04
    needs: [youki-build]
    timeout-minutes: 40
    strategy:
      matrix:
        arch: [ "x86_64" ]
        libc: [ "gnu", "musl" ]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-go@v5
        with:
          go-version: '1.23.5'
          cache: true
      - run: sudo apt-get -y update
      - run: sudo apt-get install -y pkg-config libsystemd-dev libelf-dev libseccomp-dev btrfs-progs libbtrfs-dev
      - name: Download youki binary
        uses: actions/download-artifact@v4
        with:
          name: youki-${{ matrix.arch }}-${{ matrix.libc }}
      - name: youki
        run: |
          sudo chmod 755 youki
      - name: Setup Bats and bats libs
        uses: bats-core/bats-action@3.0.1
        with:
          bats-version: 1.9.0
          support-install: false
          assert-install: false
          detik-install: false
          file-install: false
      - name: runc integration tests
        run: scripts/runc_integration.sh